language: php

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
    - composer update $COMPOSER_FLAGS
    - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit -v --coverage-text
